repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .*\.edf
      - id: end-of-file-fixer
        exclude: .*\.edf
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix", "--indent", "4", "--no-sort-keys"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ["-d {ignore: deploy/worker/.*yaml}", "-s"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py310-plus"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-simplify
          - flake8-black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        # .bandit config is not read when used by
        # pre-commit (ie with explicit file in input)
        # https://github.com/PyCQA/bandit/issues/332
        args: ["--skip", "B101"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        types: [python]
        args: ["--ignore-missing-imports", "--check-untyped-defs"]
        additional_dependencies:
          [pydantic, types-pytz, types-requests, types-protobuf]
