[project]
name = "python_phenoage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic", "pandas", "numpy", "pyaging", "requests>=2.32.4"]

[dependency-groups]
dev = ["ruff>=0.11.13", "pytest", "pre-commit>=4.2.0", "black", "coverage"]
